# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://subash-aryal.com.np/
baseurl: ""
title: My Website
author: Subash Aryal
description: Personal blog and resume
avatar: profile.png
email: aryal.subash@yahoo.com
github: blacpythoz # username
twitter: subasharyal
linkedin: subasharyal
stackoverflow: blacpythoz   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: subash
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
